// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhuomwucgjfhcombosgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxodW9td3VjZ2pmaGNvbWJvc2d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDk3OTQsImV4cCI6MjA2NTQ4NTc5NH0.au9SPv3IFqmjPla86A-GkpxCvDrorGmxtXXVsK4t2uQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);